# Generated by Django 2.2.3 on 2020-04-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_articles_document_researchpapers_snowballing_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snowballing_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
