# Generated by Django 2.2.3 on 2020-05-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_snowballing_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snowballing_articles',
        ),
    ]
