# Generated by Django 2.2.3 on 2020-05-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_snowballing_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSearch_Datatable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('Year', models.IntegerField(blank=True, max_length=100)),
                ('Url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['Title'],
            },
        ),
    ]
